server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PpureeSong/spring-cloud
#          uri: file:///Users/haddudda/dev/spring-cloud/git-local-repo
